import 'dart:async';
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:fomate_frontend/localstorage/user_localstorage.dart';
import 'package:fomate_frontend/model/model.dart';
import 'package:fomate_frontend/utils/colors.dart';
import 'package:fomate_frontend/view/widgets/widgets.dart';
import 'package:fomate_frontend/viewmodel/viewmodel.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:fomate_frontend/data/response/status.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:fluttertoast/fluttertoast.dart';

part 'logoloading_page.dart';
part 'blueloading(1)_page.dart';
part 'blueloading(2)_page.dart';
part 'mainmenu_page.dart';
part 'register_page.dart';
part 'login_page.dart';
part 'home_page.dart';
part 'contentlist_page.dart';
part 'contentdetail_page.dart';
part 'pricing_page.dart';
part 'payment_lifetimedeal_page.dart';
part 'payment_singledeal_page.dart';